import { useMemo, useState } from "react";

import { openBackupExportFolderDialog, openBackupImportDialog } from "../services/modsFolderDialog";
import { exportSongBackup, importSongBackup } from "../services/scanModsApi";
import type { ScannedSong, ScannedSongMetadata, SongBackupRow } from "../types/scanMods";

type Field = "included" | "artist" | "title" | "year" | "genre" | "gameicon";
type Props = { songs: ScannedSong[]; includedSongPaths: string[]; draftMetadata: Record<string, ScannedSongMetadata>; onApply: (metadata: Record<string, ScannedSongMetadata>, included: Record<string, boolean>) => void; onClose: () => void; onExported: (path: string) => void };
type Change = { path: string; folder: string; fields: Array<{ field: Field; before: string; after: string }>; metadata: ScannedSongMetadata; included: boolean };

const fields: Field[] = ["included", "artist", "title", "year", "genre", "gameicon"];
const labels: Record<Field, string> = { included: "Included", artist: "Artist", title: "Title", year: "Year", genre: "Genre", gameicon: "GameIcon" };
const normalize = (value: string) => value.replace(/\\/g, "/").replace(/^\.\//, "").toLocaleLowerCase();
const folderOf = (path: string) => {
  const normalized = path.replace(/\\/g, "/");
  const separator = normalized.lastIndexOf("/");
  return separator === -1 ? "" : normalized.slice(0, separator);
};

export function BackupWizard({ songs, includedSongPaths, draftMetadata, onApply, onClose, onExported }: Props) {
  const [mode, setMode] = useState<"choose" | "import" | "review">("choose");
  const [selected, setSelected] = useState<Record<Field, boolean>>(() => Object.fromEntries(fields.map((field) => [field, true])) as Record<Field, boolean>);
  const [rows, setRows] = useState<SongBackupRow[]>([]); const [error, setError] = useState("");
  const included = useMemo(() => new Set(includedSongPaths), [includedSongPaths]);
  const preview = useMemo(() => buildPreview(rows, songs, included, draftMetadata, selected), [draftMetadata, included, rows, selected, songs]);
  async function exportAll() { setError(""); const destination = await openBackupExportFolderDialog(); if (!destination || Array.isArray(destination)) return; try { const result = await exportSongBackup(destination, songs.map((song) => { const metadata = draftMetadata[song.relative_path] ?? song; return { checksum: song.checksum, included: included.has(song.relative_path), artist: metadata.artist, title: metadata.title, year: metadata.year, genre: metadata.genre, gameicon: metadata.game_icon, relative_folder: folderOf(song.relative_path) }; })); onExported(result.path); onClose(); } catch (err) { setError(String(err)); } }
  async function chooseImport() { setError(""); const path = await openBackupImportDialog(); if (!path || Array.isArray(path)) return; try { setRows(await importSongBackup(path)); setMode("import"); } catch (err) { setError(String(err)); } }
  function finish() { const metadata: Record<string, ScannedSongMetadata> = {}; const nextIncluded: Record<string, boolean> = {}; preview.changes.forEach((change) => { metadata[change.path] = change.metadata; nextIncluded[change.path] = change.included; }); onApply(metadata, nextIncluded); onClose(); }
  return <div className="scan-wizard-backdrop" role="presentation"><section className="scan-wizard-panel backup-panel" role="dialog" aria-modal="true" aria-labelledby="backup-title"><div className="scan-wizard-header"><div><p className="scan-wizard-step">{mode === "review" ? "Step 3 of 3" : mode === "choose" ? "Step 1 of 3" : "Step 2 of 3"}</p><h2 id="backup-title">Song backup</h2></div><button className="close-btn" type="button" onClick={onClose} aria-label="Close backup wizard">&times;</button></div><div className="scan-wizard-body">{mode === "choose" && <p className="scan-wizard-summary">Export creates a CSV backup from the current table state, including unsaved changes. Import reads a backup and lets you review changes before updating only the UI.</p>}{mode === "import" && <><p className="scan-wizard-summary">Select which values to import.</p><div className="backup-fields">{fields.map((field) => <label key={field}><input type="checkbox" checked={selected[field]} onChange={(event) => setSelected((current) => ({ ...current, [field]: event.target.checked }))} /> {labels[field]}</label>)}</div></>}{mode === "review" && <><p className="scan-wizard-summary">{preview.changes.length} songs will receive UI-only changes. No song.ini files will be saved.</p><div className="backup-review-groups">{preview.changes.map((change) => <section className="backup-review-card" key={change.path}><div className="backup-review-card-header">{change.folder || "<MODS root>"}</div><div>{change.fields.map((field) => <div className="backup-review-change" key={field.field}><span className="backup-change-label">{labels[field.field]}:</span><span>{field.before || "<empty>"}</span><span className="backup-change-arrow">→</span><span>{field.after || "<empty>"}</span></div>)}</div></section>)}</div><h3>Skipped CSV rows ({preview.skipped.length})</h3>{preview.skipped.map((item, index) => <p className="scan-wizard-muted" key={`${item.checksum}-${item.folder}-${index}`}>{item.checksum || "<empty checksum>"} — {item.folder || "<empty folder>"}: {item.reason}</p>)}</>}</div>{error && <p className="scan-wizard-error">{error}</p>}<div className="scan-wizard-actions">{mode === "choose" && <><button className="secondary-btn" type="button" onClick={() => void chooseImport()}>Import</button><button className="primary-btn" type="button" onClick={() => void exportAll()}>Export</button></>}{mode === "import" && <><button className="secondary-btn" type="button" onClick={() => setMode("choose")}>Back</button><button className="primary-btn" type="button" onClick={() => setMode("review")}>Next</button></>}{mode === "review" && <><button className="secondary-btn" type="button" onClick={() => setMode("import")}>Back</button><button className="primary-btn" type="button" onClick={finish}>Finish import</button></>}</div></section></div>;
}

function buildPreview(rows: SongBackupRow[], songs: ScannedSong[], included: Set<string>, drafts: Record<string, ScannedSongMetadata>, selected: Record<Field, boolean>) {
  const groups = new Map<string, ScannedSong[]>(); songs.forEach((song) => groups.set(normalize(song.checksum), [...(groups.get(normalize(song.checksum)) ?? []), song]));
  const duplicateRows = new Set<string>(); const rowCounts = new Map<string, number>(); rows.forEach((row) => { const key = `${normalize(row.checksum)}|${normalize(row.relative_folder)}`; rowCounts.set(key, (rowCounts.get(key) ?? 0) + 1); }); rowCounts.forEach((count, key) => { if (count > 1) duplicateRows.add(key); });
  const changes: Change[] = []; const skipped: Array<{ checksum: string; folder: string; reason: string }> = [];
  rows.forEach((row) => { const key = `${normalize(row.checksum)}|${normalize(row.relative_folder)}`; if (duplicateRows.has(key)) { skipped.push({ checksum: row.checksum, folder: row.relative_folder, reason: "Duplicate CSV checksum and folder." }); return; } const matches = groups.get(normalize(row.checksum)) ?? []; let song = matches.length === 1 ? matches[0] : matches.filter((candidate) => normalize(folderOf(candidate.relative_path)) === normalize(row.relative_folder))[0]; if (!song || (matches.length > 1 && matches.filter((candidate) => normalize(folderOf(candidate.relative_path)) === normalize(row.relative_folder)).length !== 1)) { skipped.push({ checksum: row.checksum, folder: row.relative_folder, reason: matches.length ? "Checksum is duplicated and the folder did not identify one song." : "Checksum was not found." }); return; } const before = drafts[song.relative_path] ?? song; const metadata: ScannedSongMetadata = { artist: selected.artist ? row.artist : before.artist, title: selected.title ? row.title : before.title, year: selected.year ? row.year : before.year, genre: selected.genre ? row.genre : before.genre, game_icon: selected.gameicon ? row.gameicon : before.game_icon }; const nextIncluded = selected.included ? row.included : included.has(song.relative_path); const changed = fields.flatMap((field) => { const prior = field === "included" ? String(included.has(song.relative_path)) : before[field === "gameicon" ? "game_icon" : field as keyof ScannedSongMetadata]; const next = field === "included" ? String(nextIncluded) : metadata[field === "gameicon" ? "game_icon" : field as keyof ScannedSongMetadata]; return selected[field] && prior !== next ? [{ field, before: prior, after: next }] : []; }); if (changed.length) changes.push({ path: song.relative_path, folder: folderOf(song.relative_path), fields: changed, metadata, included: nextIncluded }); }); return { changes, skipped };
}
